image: "rust:latest"

variables:
  CARGO_TERM_COLOR: always

stages:
  - build
  - zip
  - create_artifact

build_linux:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev
    - cargo install tauri-cli
    - cargo tauri build
  tags:
    - ubuntu

zip_linux:
  stage: zip
  script:
    - zip -r cazic_linux.zip target/release/bundle/*deb target/release/bundle/appimage/*
  artifacts:
    paths:
      - cazic_linux.zip
  tags:
    - ubuntu

build_windows:
  stage: build
  script:
    - cargo install tauri-cli
    - cargo tauri build
  tags:
    - windows

zip_windows:
  stage: zip
  script:
    - Compress-Archive -Path target/release/bundle/nsis/*exe,target/release/bundle/msi/*msi -DestinationPath cazic_windows.zip
  artifacts:
    paths:
      - cazic_windows.zip
  tags:
    - windows

create_artifact:
  stage: create_artifact
  dependencies:
    - zip_linux
    - zip_windows
  script:
    - echo "Creating artifacts..."
  artifacts:
    paths:
      - cazic_linux.zip
      - cazic_windows.zip