stages:
  - linux
  - windows

variables:
  CARGO_TERM_COLOR: always

linux:
  stage: linux
  image: rust:latest
  script:
    - rustup target add aarch64-unknown-linux-gnu
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
    - cargo install tauri-cli
    - cargo-tauri build
    - cargo-tauri build --target aarch64-unknown-linux-gnu
    - tar -czf cazic_linux.tar.gz target/debug/cazic

  artifacts:
    paths:
      - cazic_linux.tar.gz
    expire_in: 1 week

windows:
  stage: windows
  image: rust:latest
  script:
    - rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev mingw-w64
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-pc-windows-msvc
    - cargo-tauri build --target aarch64-pc-windows-msvc
    - tar -czf cazic_windows.tar.gz target/x86_64-pc-windows-msvc/debug/cazic.exe target/aarch64-pc-windows-msvc/debug/cazic.exe target/x86_64-pc-windows-msvc/debug/WebView2Loader.dll target/aarch64-pc-windows-msvc/debug/WebView2Loader.dll

  artifacts:
    paths:
      - cazic_windows.tar.gz
    expire_in: 1 week