stages:
  - pipeline

variables:
  CARGO_TERM_COLOR: always

build:
  stage: pipeline
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup --noconfirm
    - rustup toolchain install stable --profile minimal
    - pacman -S --needed webkit2gtk base-devel curl wget file openssl appmenu-gtk-module gtk3 libappindicator-gtk3 librsvg libvips 
    - cargo install tauri-cli
    - cargo build build
    - tar -czf cazic_linux.tar.gz target/release/bundle/*deb target/release/bundle/appimage/*
    - tar -czf cazic_windows.tar.gz target/release/bundle/nsis/*exe target/release/bundle/msi/*msi
  artifacts:
    paths:
      - cazic_linux.tar.gz
      - cazic_windows.tar.gz
    expire_in: 1 week