stages:
  - linux
  - windows
  - macos
  - android

variables:
  CARGO_TERM_COLOR: always

linux:
  stage: linux
  image: rust:latest
  script:
    - rustup target add aarch64-unknown-linux-gnu
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
    - cargo install tauri-cli
    - tauri build
    - tauri build --target aarch64-unknown-linux-gnu
    - tar -czf cazic_linux.tar.gz target/debug/cazic

  artifacts:
    paths:
      - cazic_linux.tar.gz
    expire_in: 1 week

windows:
  stage: windows
  image: rust:latest
  script:
    - rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev mingw-w64
    - cargo install tauri-cli
    - tauri build --target x86_64-pc-windows-msvc
    - tauri build --target aarch64-pc-windows-msvc
    - tar -czf cazic_windows.tar.gz target/x86_64-pc-windows-msvc/debug/cazic.exe target/aarch64-pc-windows-msvc/debug/cazic.exe target/x86_64-pc-windows-msvc/debug/WebView2Loader.dll target/aarch64-pc-windows-msvc/debug/WebView2Loader.dll

  artifacts:
    paths:
      - cazic_windows.tar.gz
    expire_in: 1 week

macos:
  stage: macos
  image: rust:latest
  script:
    - rustup target add x86_64-apple-darwin aarch64-apple-darwin
    - brew install openssl@1.1 libwebkit2gtk
    - cargo install tauri-cli
    - tauri build --target x86_64-apple-darwin
    - tauri build --target aarch64-apple-darwin
    - tar -czf cazic_macos.tar.gz target/x86_64-apple-darwin/debug/cazic target/aarch64-apple-darwin/debug/cazic

  artifacts:
    paths:
      - cazic_macos.tar.gz
    expire_in: 1 week

android:
  stage: android
  image: rust:latest
  script:
    - rustup target add aarch64-linux-android arm-linux-androideabi armv7-linux-androideabi
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
    - cargo install tauri-cli
    - tauri build --target aarch64-linux-android
    - tauri build --target arm-linux-androideabi
    - tauri build --target armv7-linux-androideabi
    - tar -czf cazic_android.tar.gz target/aarch64-linux-android/debug/cazic.apk target/arm-linux-androideabi/debug/cazic.apk target/armv7-linux-androideabi/debug/cazic.apk

  artifacts:
    paths:
      - cazic_android.tar.gz
    expire_in: 1 week