stages:
  - pipeline

variables:
  CARGO_TERM_COLOR: always

build:
  stage: pipeline
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup --noconfirm
    - rustup toolchain install stable --profile minimal
    - pacman -S --needed webkit2gtk base-devel curl wget file openssl appmenu-gtk-module gtk3 libappindicator-gtk3 librsvg libvips --noconfirm
    - cargo install tauri-cli
    - cargo tauri dev
    - tar -czf cazic_linux.tar.gz target/debug/cazic

  artifacts:
    paths:
      - cazic_linux.tar.gz
    expire_in: 1 week