steps:
  - name: linux
    image: rust:latest
    environment: [CARGO_TERM_COLOR=always]
    script:
      - |
        rustup default stable
        apt-get update
        apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev;
        cargo install tauri-cli
        cargo tauri build
