
steps:
  rust:
    image: rust
    commands:
      - rustup toolchain install --profile=minimal stable 

  tauri:
    image: rust
    commands:
      - cargo install tauri-cli

  install-dependencies-linux:
    image: ubuntu
    commands:
      - sudo apt-get update; sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev

  build:
    image: rust
    commands:
      - cargo tauri build

  zip-artifact:
    image: ubuntu
    commands:
      - zip cazic_linux.zip target/release/bundle/*deb target/release/bundle/appimage/*AppImage -r

  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
        base_url: https://codeberg.org
        files:
          - "cazic_linux.zip"
        checksum:
          - sha256
        api_key:
          from_secret: GITEA_ACCESS_TOKEN
