name: Cazic_fix-app-crash-when-discord-down

on:
  push:
    branches: ["fix-app-crash-when-discord-down"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Tauri
        run: cargo install tauri-cli

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update; sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev

      - name: Build
        run: cargo tauri build

      - name: Zip Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: zip cazic_linux.zip target/release/bundle/*deb target/release/bundle/appimage/*AppImage -r

      - name: Zip Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path target/release/bundle/nsis/*exe,target/release/bundle/msi/*msi -DestinationPath cazic_windows.zip

      - name: Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Cazic (Linux)
          path: cazic_linux.zip

      - name: Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Cazic (Windows)
          path: cazic_windows.zip
